resource-pack: https://www.dropbox.com/s/a0tvp6mris6xjg0/TankPackV23.zip?dl=1

# Vehicle Sleep Settings
# Vehicle sleep is when the vehicle stops being calculated for physics and other events
# This means that they are uninteractable and will be woken up when someone tries to open them
# Trailers dont sleep (except on server reset)

# How many mins until the vehicle shall "sleep"
sleep-time: 5

# Should we wake vehicles around players constantly?
# Can cause excess lag
auto-wakeup: false
# How often should we wakeup vehicles around players (seconds, no decimals)
auto-wakeup-time: 60


armor-repair-cost: 200
component-repair-cost: 200
scrap-reward: 500

fuelTypes:
    # Name of fuel
    diesel:
        name: Diesel
        # Density of fuel
        # 1 = 1 fuel used up per fuel tick (ish)
        # 0.5 = 2 fuel used up per tick (ish)
        # fuel = fuelConsumptionAmount/fuelDensity
        fuelDensity: 1
        # Amount of money to give per fuel "unit"
        # 200 fuel at a rate of 5 will cost 1000
        fuelExchangeRate: 5
        # Icon to display the fuel type as
        matIcon: COAL_BLOCK
    jetFuel:
        name: Jet Fuel
        fuelDensity: 10
        fuelExchangeRate: 100
        matIcon: FIRE_CHARGE